name: Enectiva
markdown: redcarpet
highlighter: true

encoding: UTF-8

url: http://enectiva.cz

gems:
- jekyll-compass
- jekyll-assets
- jekyll-paginate

assets:
  dirname: assets-web
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  digest: true
  gzip:
    - text/css
    - application/javascript
    - image/svg+xml
    - application/vnd.ms-fontobject
    - application/font-woff
    - application/x-font-woff
    - application/font-stnt
    - application/octet-stream

exclude:
- readme.md
- Gemfile
- Gemfile.lock

permalink:  /:categories/:year/:month/:title

paginate: 5
paginate_path: /blog/page-:num
paginate_per_category: true
default_category: cs

authorized_locales: [cs, en, it, es, de]
default_locale: cs

cs:
  prev: Novější
  next: Starší
en:
  prev: Newer
  next: Older

prose:
  rooturl: ""
  siteurl: "http://enectiva.cz/"
  media: "img"
  metadata:
    cs:
      - &KEYWORDS_CS
        name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Dodatečná klíčová slova"
          placeholder: "Mělo by začínat ,"
    en:
      - &KEYWORDS_EN
        name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Extra keywords"
          placeholder: "Start with ,"
    it:
      - &KEYWORDS_IT
        name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Extra keywords"
          placeholder: "Start with ,"
    es:
      - &KEYWORDS_ES
        name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Extra keywords"
          placeholder: "Start with ,"
    de:
      - &KEYWORDS_DE
        name: "keywords"
        field:
          element: "text"
          type: "text"
          label: "Extra keywords"
          placeholder: "Start with ,"
    _solutions/cs:
      - *KEYWORDS_CS
    _solutions/en:
      - *KEYWORDS_EN
    _solutions/it:
      - *KEYWORDS_IT
    _solutions/es:
      - *KEYWORDS_ES
    _solutions/de:
      - *KEYWORDS_DE
    cs/blog/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          type: "text"
          placeholder: "Název článku"
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Autor"
          placeholder: "(z /config/authors.yml)"
      - *KEYWORDS_CS
    en/blog/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          type: "text"
          placeholder: "Post title"
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Author"
          placeholder: "(from /config/authors.yml)"
      - *KEYWORDS_EN
